from __future__ import annotations
from typing import Any
from airedteam.core.types import Prompt, Response, Message, AttemptResult


class MultiTurnExecutor:
    """Abstract base for multi-turn attacks.

    Subclasses implement ``next_user_message`` (how to craft the next user turn
    given the state so far) and optionally ``should_stop`` to bail out early.

    The first user turn is seeded from the dataset ``Prompt`` and is the only
    turn that converters are applied to — subsequent turns are assumed to be
    generated by the attack strategy itself.

    ``state`` is a free-form dict the subclass owns. The base manages
    ``state['turn']`` (0-indexed turn counter), ``state['conversation']``
    (list[Message]), ``state['seed']`` (the original dataset Prompt *before*
    conversion), and ``state['first_user']`` (the converted first user Prompt).
    """
    name: str = "multi_turn_base"
    max_turns: int = 5

    async def next_user_message(
        self, state: dict[str, Any], last_response: Response | None,
    ) -> Message | None:
        raise NotImplementedError

    async def should_stop(
        self, state: dict[str, Any], last_response: Response | None,
    ) -> bool:
        return state["turn"] >= self.max_turns

    async def on_turn(
        self, state: dict[str, Any], user: Message, assistant: Response,
    ) -> None:
        """Hook for subclasses (e.g. PAIR's judge between turns). Default no-op."""
        return None

    async def run(self, prompt: Prompt, target, converters: list) -> AttemptResult:
        chain: list[str] = []
        cur = prompt
        for c in converters:
            cur = await c.convert(cur)
            chain.append(c.name)

        state: dict[str, Any] = {
            "turn": 0,
            "conversation": [],
            "seed": prompt,
            "first_user": cur,
        }
        last_response: Response | None = None
        last_user: Message | None = None

        try:
            while True:
                if state["turn"] == 0:
                    user = Message(role="user", text=cur.text)
                else:
                    nxt = await self.next_user_message(state, last_response)
                    if nxt is None:
                        break
                    user = nxt

                state["conversation"].append(user)
                last_user = user
                last_response = await target.chat(list(state["conversation"]))
                state["conversation"].append(
                    Message(role="assistant", text=last_response.text)
                )
                await self.on_turn(state, user, last_response)
                state["turn"] += 1
                if await self.should_stop(state, last_response):
                    break

            return AttemptResult(
                prompt=Prompt(text=state["first_user"].text, metadata=prompt.metadata),
                response=last_response,
                status="completed",
                converter_chain=chain,
                conversation=list(state["conversation"]),
            )
        except Exception as e:
            return AttemptResult(
                prompt=Prompt(text=(last_user.text if last_user else cur.text)),
                response=last_response,
                status="failed",
                error=f"{type(e).__name__}: {e}",
                converter_chain=chain,
                conversation=list(state["conversation"]),
            )
